### ISSUE TITLE
Should we rename UPClientZenoh to UPTransportZenoh?

### ISSUE THREAD

**Issue by evshary** [eclipse-uprotocol/up-transport-zenoh-rust#44]
Since now we rename the project to `up-transport-zenoh-rust`, I'm wondering whether we should rename the struct.
@PLeVasseur WDYT?

**Comment by PLeVasseur** [comment]
I dunno, kinda why I wasn't sure renaming the projects to up-transport-... was good in the first place, since it's possible we want to have dedicated means of implementing uP-L2 APIs (e.g. RpcClient) within the up-transport-...  repos.

IMHO since you're not implementing _only_ the uP-L1 UTransport it makes sense to keep it named as UPClientZenoh.

My 2 cents.

**Comment by evshary** [comment]
Make sense. Let's close the issue temporarily.
